name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build executable for release
        run: swift build -c release
      - name: Compress archive
        run: zip -r -q StringifyMacroMacros${{ github.ref_name }}.zip .build/arm64-apple-macosx/release/StringifyMacroMacros
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.ref_name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install bundle
        run: bundle install
      - name: Bump podspec version
        run: bundle exec fastlane run version_bump_podspec path:"StringifyMacro.podspec" version_number:"${{ github.ref_name }}"
      - name: Commit podspec
        run: |
          git add StringifyMacro.podspec
          git diff --quiet && git diff --staged --quiet || git commit -m "[🤖 release] Bump podspec version to ${{ github.ref_name }}"
          git push origin main
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
